# Generated by Django 6.0.3 on 2026-04-01 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AporteAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aporte_asignado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aporte', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_limite', models.DateField()),
                ('estado_ap', models.CharField(choices=[('APORTADO', 'Aportado'), ('PERDIDO', 'Perdido'), ('PENDIENTE', 'Pendiente')], max_length=15)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aporte de Ahorro',
                'verbose_name_plural': 'Aportes de Ahorro',
            },
        ),
        migrations.CreateModel(
            name='AhorroMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_meta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_acumulado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frecuencia', models.CharField(choices=[('DIARIA', 'Diaria'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], max_length=15)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_meta', models.DateField()),
                ('estado', models.CharField(choices=[('SIN_INICIAR', 'Sin_iniciar'), ('ACTIVO', 'Activo'), ('COMPLETADO', 'Completado'), ('ABANDONADO', 'Abandonado')], default='SIN_INICIAR', max_length=25)),
                ('cantidad_cuotas', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=150)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
            ],
            options={
                'verbose_name': 'Meta de Ahorro',
                'verbose_name_plural': 'Metas de Ahorro',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
