# Generated by Django 5.2 on 2026-03-12 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AhorroMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoMeta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('totalAcumulado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frecuencia', models.CharField(choices=[('DIARIA', 'Diaria'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], max_length=15)),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('fechaMeta', models.DateField(blank=True)),
                ('estado', models.BooleanField()),
                ('cantidadCuotas', models.IntegerField()),
                ('descripcion', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta de Ahorro',
                'verbose_name_plural': 'Metas de Ahorro',
                'ordering': ['-fechaCreacion'],
            },
        ),
        migrations.CreateModel(
            name='AporteAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aporteAsignado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aporte', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fechaLimite', models.DateField()),
                ('estadoAp', models.BooleanField()),
                ('fechaRegistro', models.DateField(auto_now_add=True)),
                ('ahorro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahorros.ahorrometa')),
            ],
            options={
                'verbose_name': 'Aporte de Ahorro',
                'verbose_name_plural': 'Aportes de Ahorro',
            },
        ),
    ]
