# Generated by Django 6.0.3 on 2026-04-01 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ahorros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ahorrometa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aporteahorro',
            name='ahorro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahorros.ahorrometa'),
        ),
    ]
