# Generated by Django 5.2 on 2026-06-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aporteahorro',
            name='es_extraordinario',
            field=models.BooleanField(default=False),
        ),
    ]
