# Generated by Django 5.2 on 2026-03-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahorrometa',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
