# Generated by Django 5.2 on 2026-03-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorros', '0002_alter_ahorrometa_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ahorrometa',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Meta de Ahorro', 'verbose_name_plural': 'Metas de Ahorro'},
        ),
        migrations.RenameField(
            model_name='ahorrometa',
            old_name='cantidadCuotas',
            new_name='cantidad_cuotas',
        ),
        migrations.RenameField(
            model_name='ahorrometa',
            old_name='fechaCreacion',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='ahorrometa',
            old_name='montoMeta',
            new_name='monto_meta',
        ),
        migrations.RenameField(
            model_name='ahorrometa',
            old_name='totalAcumulado',
            new_name='total_acumulado',
        ),
        migrations.RenameField(
            model_name='aporteahorro',
            old_name='aporteAsignado',
            new_name='aporte_asignado',
        ),
        migrations.RenameField(
            model_name='aporteahorro',
            old_name='fechaLimite',
            new_name='fecha_limite',
        ),
        migrations.RenameField(
            model_name='aporteahorro',
            old_name='fechaRegistro',
            new_name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='ahorrometa',
            name='fechaMeta',
        ),
        migrations.RemoveField(
            model_name='aporteahorro',
            name='estadoAp',
        ),
        migrations.AddField(
            model_name='ahorrometa',
            name='fecha_meta',
            field=models.DateField(default='2026-08-08'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aporteahorro',
            name='estado_ap',
            field=models.CharField(choices=[('APORTADO', 'Aportado'), ('PERDIDO', 'Perdido'), ('PENDIENTE', 'Pendiente')], default='2026-04-04', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ahorrometa',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='ahorrometa',
            name='estado',
            field=models.CharField(choices=[('SIN_INICIAR', 'Sin_iniciar'), ('ACTIVO', 'Activo'), ('COMPLETADO', 'Completado'), ('ABANDONADO', 'Abandonado')], max_length=25),
        ),
    ]
