# Generated by Django 5.2 on 2026-03-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorros', '0003_alter_ahorrometa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahorrometa',
            name='estado',
            field=models.CharField(choices=[('SIN_INICIAR', 'Sin_iniciar'), ('ACTIVO', 'Activo'), ('COMPLETADO', 'Completado'), ('ABANDONADO', 'Abandonado')], default='SIN_INICIAR', max_length=25),
        ),
        migrations.AlterField(
            model_name='ahorrometa',
            name='total_acumulado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='aporteahorro',
            name='aporte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
