# Generated by Django 5.2 on 2026-04-22 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente_financiero', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertas_json', models.JSONField()),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('visto_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_diarias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generado_en'],
            },
        ),
    ]
