# Generated by Django 5.2 on 2026-05-23 00:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente_financiero', '0002_alertadiaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertadiaria',
            name='generado_en',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='mensajechat',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='alertadiaria',
            index=models.Index(fields=['usuario', '-generado_en'], name='agente_fina_usuario_3a63c5_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajechat',
            index=models.Index(fields=['usuario', '-creado_en'], name='agente_fina_usuario_d0d03b_idx'),
        ),
    ]
