# Generated by Django 6.0.3 on 2026-04-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('UMBRAL_MENSUAL', 'Umbral mensual alcanzado'), ('EGRESO_GRANDE', 'Egreso grande registrado'), ('DEFICIT', 'Balance en déficit'), ('GASTO_INCREMENTAL', 'Gasto incremental detectado'), ('REDUCCION_INGRESOS', 'Reducción de ingresos detectada'), ('PATRON_INUSUAL', 'Patrón inusual de gastos'), ('CONCENTRACION_GASTO', 'Concentración de gastos en concepto'), ('CONCEPTO_SIN_USO', 'Concepto recurrente sin actividad'), ('VELOCIDAD_GASTO', 'Velocidad de gasto alta'), ('INACTIVIDAD_INGRESOS', 'Inactividad de ingresos'), ('EGRESOS_AGRUPADOS', 'Múltiples gastos en corto tiempo'), ('MICRO_GASTOS', 'Múltiples micro-gastos detectados'), ('GASTOS_HORMIGA', 'Gastos hormiga diarios'), ('PROYECCION_SOBREGASTO', 'Proyección de sobregasto'), ('COMPARACION_PERIODO', 'Comparación con mes anterior'), ('DIA_MES_CRITICO', 'Día del mes crítico'), ('EGRESO_SIN_CONCEPTO', 'Egresos sin categorizar'), ('INGRESO_INUSUAL', 'Ingreso inusualmente alto')], max_length=30)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
