# Generated by Django 5.2 on 2026-05-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='referencia_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='referencia_tipo',
            field=models.CharField(blank=True, help_text="Ej: 'movimiento', 'ahorro', 'programacion', 'sistema'", max_length=20, null=True),
        ),
    ]
