# Generated by Django 5.2 on 2026-05-27 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_notificacion_referencia_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciasAlertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral_advertencia_porcentaje', models.PositiveSmallIntegerField(default=80)),
                ('egreso_grande_porcentaje', models.PositiveSmallIntegerField(default=30)),
                ('alerta_egreso_grande_activa', models.BooleanField(default=True)),
                ('alert_gasto_incremental_enabled', models.BooleanField(default=True)),
                ('alert_gasto_incremental_porcentaje', models.PositiveSmallIntegerField(default=25)),
                ('alert_gasto_incremental_meses', models.PositiveSmallIntegerField(default=3)),
                ('alert_reduccion_ingresos_enabled', models.BooleanField(default=True)),
                ('alert_reduccion_ingresos_porcentaje', models.PositiveSmallIntegerField(default=20)),
                ('alert_patron_inusual_enabled', models.BooleanField(default=True)),
                ('alert_concentracion_gastos_enabled', models.BooleanField(default=True)),
                ('alert_concentracion_gastos_porcentaje', models.PositiveSmallIntegerField(default=50)),
                ('alert_concepto_sin_uso_enabled', models.BooleanField(default=False)),
                ('alert_concepto_sin_uso_dias', models.PositiveSmallIntegerField(default=30)),
                ('alert_velocidad_gasto_enabled', models.BooleanField(default=True)),
                ('alert_inactividad_ingresos_enabled', models.BooleanField(default=True)),
                ('alert_inactividad_dias', models.PositiveSmallIntegerField(default=7)),
                ('alert_egresos_agrupados_enabled', models.BooleanField(default=True)),
                ('alert_egresos_agrupados_cantidad', models.PositiveSmallIntegerField(default=5)),
                ('alert_egresos_agrupados_horas', models.PositiveSmallIntegerField(default=2)),
                ('meta_ahorro_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('alert_meta_ahorro_enabled', models.BooleanField(default=False)),
                ('alert_balance_critico_enabled', models.BooleanField(default=True)),
                ('alert_micro_gastos_enabled', models.BooleanField(default=True)),
                ('alert_micro_gastos_cantidad', models.PositiveSmallIntegerField(default=10)),
                ('alert_micro_gastos_monto_max', models.DecimalField(decimal_places=2, default=10000, max_digits=12)),
                ('alert_gastos_hormiga_enabled', models.BooleanField(default=True)),
                ('alert_gastos_hormiga_monto_dia', models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ('alert_proyeccion_sobregasto_enabled', models.BooleanField(default=True)),
                ('alert_comparacion_periodo_enabled', models.BooleanField(default=True)),
                ('alert_dia_mes_critico_enabled', models.BooleanField(default=True)),
                ('alert_dia_mes_critico_porcentaje', models.PositiveSmallIntegerField(default=70)),
                ('alert_egreso_sin_concepto_enabled', models.BooleanField(default=False)),
                ('alert_egreso_sin_concepto_cantidad', models.PositiveSmallIntegerField(default=5)),
                ('alert_ingreso_inusual_enabled', models.BooleanField(default=True)),
                ('alert_ingreso_inusual_multiplicador', models.DecimalField(decimal_places=2, default=2.5, max_digits=4)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prefs_alertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencias de Alerta',
                'verbose_name_plural': 'Preferencias de Alertas',
            },
        ),
    ]
