# Generated by Django 5.2 on 2026-03-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_alter_notificacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('UMBRAL_MENSUAL', 'Umbral mensual alcanzado'), ('EGRESO_GRANDE', 'Egreso grande registrado'), ('DEFICIT', 'Balance en déficit')], max_length=20),
        ),
    ]
