# Generated by Django 5.2 on 2026-04-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='modulo',
            field=models.CharField(choices=[('INGRESOS', 'Ingresos'), ('EGRESOS', 'Egresos'), ('AHORROS', 'Ahorros'), ('PRESUPUESTOS', 'Presupuestos'), ('PLANIFICACION', 'Planificacion'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
    ]
