# Generated by Django 5.2 on 2026-05-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_preferenciasalertas'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciasalertas',
            name='alert_recordatorio_ahorro_dias',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='preferenciasalertas',
            name='alert_recordatorio_ahorro_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('UMBRAL_MENSUAL', 'Umbral mensual alcanzado'), ('EGRESO_GRANDE', 'Egreso grande registrado'), ('DEFICIT', 'Balance en déficit'), ('GASTO_INCREMENTAL', 'Gasto incremental detectado'), ('REDUCCION_INGRESOS', 'Reducción de ingresos detectada'), ('PATRON_INUSUAL', 'Patrón inusual de gastos'), ('CONCENTRACION_GASTO', 'Concentración de gastos en concepto'), ('CONCEPTO_SIN_USO', 'Concepto recurrente sin actividad'), ('VELOCIDAD_GASTO', 'Velocidad de gasto alta'), ('INACTIVIDAD_INGRESOS', 'Inactividad de ingresos'), ('EGRESOS_AGRUPADOS', 'Múltiples gastos en corto tiempo'), ('MICRO_GASTOS', 'Múltiples micro-gastos detectados'), ('GASTOS_HORMIGA', 'Gastos hormiga diarios'), ('PROYECCION_SOBREGASTO', 'Proyección de sobregasto'), ('COMPARACION_PERIODO', 'Comparación con mes anterior'), ('DIA_MES_CRITICO', 'Día del mes crítico'), ('RECORDATORIO_CUOTA_AHORRO', 'Recordatorio de cuota de ahorro'), ('EGRESO_SIN_CONCEPTO', 'Egresos sin categorizar'), ('INGRESO_INUSUAL', 'Ingreso inusualmente alto')], max_length=30),
        ),
    ]
