# Generated by Django 5.2 on 2026-05-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0004_preferenciasalertas_alert_recordatorio_ahorro_dias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferenciasalertas',
            name='alert_recordatorio_ahorro_dias',
            field=models.PositiveSmallIntegerField(default=3, help_text='Cuántos días antes de la fecha límite quieres recibir el aviso.', verbose_name='Días de anticipación para recordatorios'),
        ),
        migrations.AlterField(
            model_name='preferenciasalertas',
            name='alert_recordatorio_ahorro_enabled',
            field=models.BooleanField(default=True, help_text='Te avisaremos cuando se acerque la fecha de pago de tus ahorros.', verbose_name='Recordatorio de Cuota de Ahorro'),
        ),
    ]
