# Generated by Django 5.2 on 2026-05-22 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='fecha_fin',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='fecha_inicio',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='isActivo',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='presupuesto',
            index=models.Index(fields=['usuario', 'isActivo'], name='presupuesto_usuario_6dddd9_idx'),
        ),
        migrations.AddIndex(
            model_name='presupuesto',
            index=models.Index(fields=['usuario', 'categoria', 'isActivo'], name='presupuesto_usuario_3f918d_idx'),
        ),
        migrations.AddIndex(
            model_name='presupuesto',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='presupuesto_fecha_i_ef5b29_idx'),
        ),
    ]
