# Generated by Django 5.2 on 2026-10-03 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0004_categoriafavorita'),
        ('presupuesto', '0002_alter_presupuesto_fecha_fin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='presupuesto',
            name='presupuesto_usuario_6dddd9_idx',
        ),
        migrations.RemoveIndex(
            model_name='presupuesto',
            name='presupuesto_usuario_3f918d_idx',
        ),
        migrations.RenameField(
            model_name='presupuesto',
            old_name='isActivo',
            new_name='is_activo',
        ),
        migrations.AddIndex(
            model_name='presupuesto',
            index=models.Index(fields=['usuario', 'is_activo'], name='presupuesto_usuario_98c7d0_idx'),
        ),
        migrations.AddIndex(
            model_name='presupuesto',
            index=models.Index(fields=['usuario', 'categoria', 'is_activo'], name='presupuesto_usuario_199324_idx'),
        ),
    ]
