# Generated by Django 5.2 on 2026-03-08 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_egresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ahorros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingreso_neto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('disponible', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ganancia_acumulada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ahorro_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resumen mensual',
                'verbose_name_plural': 'Resúmenes mensuales',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('usuario', 'mes', 'anio')},
            },
        ),
    ]
