# Generated by Django 6.0.3 on 2026-04-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_egresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ahorros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingreso_neto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('disponible', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ganancia_acumulada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ahorro_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resumen mensual',
                'verbose_name_plural': 'Resúmenes mensuales',
                'ordering': ['-anio', '-mes'],
            },
        ),
    ]
