# Generated by Django 5.2 on 2026-03-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
    ]
