# Generated by Django 5.2 on 2026-05-22 23:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejecucionprogramacion',
            name='fecha_ejecutada',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ejecucionprogramacion',
            name='tipo',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='fecha_fin',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='fecha_inicio',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='frecuencia',
            field=models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('BIMESTRAL', 'Bimestral'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='proxima_ejecucion',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='ejecucionprogramacion',
            index=models.Index(fields=['usuario', 'fecha_ejecutada'], name='programacio_usuario_42c07e_idx'),
        ),
        migrations.AddIndex(
            model_name='programacion',
            index=models.Index(fields=['usuario', 'activo'], name='programacio_usuario_d5a409_idx'),
        ),
        migrations.AddIndex(
            model_name='programacion',
            index=models.Index(fields=['usuario', 'activo', 'frecuencia'], name='programacio_usuario_f38d98_idx'),
        ),
        migrations.AddIndex(
            model_name='programacion',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='programacio_fecha_i_d1f813_idx'),
        ),
    ]
