# Generated by Django 5.2 on 2026-03-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0002_programacion_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacion',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
