# Generated by Django 5.2 on 2026-04-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0003_alter_programacion_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='proxima_ejecucion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
