# Generated by Django 5.2 on 2026-04-01 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0004_programacion_proxima_ejecucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionProgramacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecutada', models.DateField()),
                ('proxima_ejecucion', models.DateField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria_nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=10)),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='programaciones.programacion')),
            ],
            options={
                'ordering': ['-fecha_ejecutada'],
            },
        ),
    ]
