# Generated by Django 5.2 on 2026-04-03 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0005_ejecucionprogramacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecucionprogramacion',
            name='descripcion_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ejecucionprogramacion',
            name='frecuencia_snapshot',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ejecucionprogramacion',
            name='programacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejecuciones', to='programaciones.programacion'),
        ),
    ]
