# Generated by Django 5.2 on 2026-04-28 22:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, help_text='Nombre visible en la app. No tiene que ser unico.', max_length=150, verbose_name='nombre de usuario')),
                ('email', models.EmailField(error_messages={'unique': 'Ya existe una cuenta con este correo electronico.'}, max_length=254, unique=True, verbose_name='correo electronico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('USER', 'Usuario')], default='USER', max_length=10)),
                ('google_id', models.CharField(blank=True, help_text='Identificador de la cuenta Google vinculada. Usado por django-allauth.', max_length=255, null=True, unique=True, verbose_name='Google ID (OAuth)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral_advertencia_porcentaje', models.IntegerField(default=80)),
                ('egreso_grande_porcentaje', models.IntegerField(default=30)),
                ('alerta_egreso_grande', models.BooleanField(default=True)),
                ('alerta_deficit', models.BooleanField(default=True)),
                ('alerta_patron_inusual', models.BooleanField(default=True)),
                ('alerta_presupuesto', models.BooleanField(default=True)),
                ('alerta_aporte_proximo', models.BooleanField(default=True)),
                ('alerta_aporte_dias_anticipacion', models.IntegerField(default=3)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
