# Generated by Django 5.2 on 2026-03-08 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral_advertencia_porcentaje', models.IntegerField(default=80)),
                ('egreso_grande_porcentaje', models.IntegerField(default=30)),
                ('alerta_egreso_grande', models.BooleanField(default=True)),
                ('alerta_deficit', models.BooleanField(default=True)),
                ('alerta_patron_inusual', models.BooleanField(default=True)),
                ('alerta_presupuesto', models.BooleanField(default=True)),
                ('alerta_aporte_proximo', models.BooleanField(default=True)),
                ('alerta_aporte_dias_anticipacion', models.IntegerField(default=3)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
