# Generated by Django 6.0.3 on 2026-04-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(blank=True, help_text='Nombre visible en la app. No tiene que ser unico.', max_length=150, verbose_name='nombre de usuario'),
        ),
    ]
