# Generated by Django 5.2 on 2026-05-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('nombre', 'tipo')},
        ),
    ]
