# Generated by Django 5.2 on 2026-05-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_categoria_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='es_sistema',
            field=models.BooleanField(default=False, help_text='Ocultar al usuario en listados de creación'),
        ),
    ]
