# Generated by Django 5.2 on 2026-03-28 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('CREACION', 'Creación'), ('EDICION', 'Edición'), ('ELIMINACION', 'Eliminación')], max_length=15)),
                ('modulo', models.CharField(choices=[('MOVIMIENTOS', 'Movimientos'), ('CATEGORIAS', 'Categorías'), ('AHORROS', 'Ahorros'), ('PRESUPUESTOS', 'Presupuestos'), ('PROYECCIONES', 'Proyecciones'), ('SISTEMA', 'Sistema')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('referencia_id', models.CharField(blank=True, max_length=50, null=True)),
                ('monto_afectado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_historial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acción de Historial',
                'verbose_name_plural': 'Acciones de Historial',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
