# Generated by Django 6.0.3 on 2026-04-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccionHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('CREACION', 'Creación'), ('EDICION', 'Edición'), ('ELIMINACION', 'Eliminación')], max_length=15)),
                ('modulo', models.CharField(choices=[('INGRESOS', 'Ingresos'), ('EGRESOS', 'Egresos'), ('CATEGORIAS', 'Categorias'), ('AHORROS', 'Ahorros'), ('PRESUPUESTOS', 'Presupuestos'), ('PROYECCIONES', 'Proyecciones'), ('SISTEMA', 'Sistema')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('referencia_id', models.CharField(blank=True, max_length=50, null=True)),
                ('monto_afectado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Acción de Historial',
                'verbose_name_plural': 'Acciones de Historial',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
