# Generated by Django 5.2 on 2026-05-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accionhistorial',
            name='modulo',
            field=models.CharField(choices=[('INGRESOS', 'Ingresos'), ('EGRESOS', 'Egresos'), ('CATEGORIAS', 'Categorias'), ('AHORROS', 'Ahorros'), ('PROGRAMACIONES', 'Programaciones'), ('PRESUPUESTOS', 'Presupuestos'), ('PROYECCIONES', 'Proyecciones'), ('SISTEMA', 'Sistema')], max_length=20),
        ),
    ]
